package jpa.service;
import java.util.List;

import javax.persistence.TypedQuery;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import jpa.dao.StudentDAO;
import jpa.entitymodels.Course;
import jpa.entitymodels.Student;

public class StudentService implements StudentDAO{

	// This method reads the student table in your database and returns the data as a List<Student>
	public List<Student> getAllStudents() {
		
		SessionFactory factory = new Configuration().configure().buildSessionFactory();
		Session session = factory.openSession();
		Transaction t = session.beginTransaction();

		String hql = "FROM Student s";

		TypedQuery<Student> query = session.createQuery(hql, Student.class);

		List<Student> result = query.getResultList();
		for (Student u : result) {
	    	 System.out.println("Email: " +u.getSEmail() + "|" + " Name:" + u.getSName() +"|"+ "Password: " + u.getSPass());
	    }

		t.commit();
		factory.close();
		session.close();

		return result;
	}

	// This method takes a Student’s email as a String and parses the student list for a Student with that email and returns a Student Object.
	public Student getStudentByEmail(String inputEmail) {
		SessionFactory factory = new Configuration().configure().buildSessionFactory();
		Session session = factory.openSession();
		Transaction t = session.beginTransaction();

		String hql = "FROM Student s WHERE s.sEmail=:email";
		TypedQuery<Student> query = session.createQuery(hql, Student.class);
		query.setParameter("email",inputEmail);
		
		Student result = query.getSingleResult();
		
		t.commit();
		factory.close();
		session.close();
		
		
		return result;
	}

	// This method takes two parameters: the first one is the user email and the second one is the password from the user input.
	// Return whether or not a student was found.
	public boolean validateStudent(String inputEmail, String inputPass) {
		
		boolean validated = false;
		SessionFactory factory = new Configuration().configure().buildSessionFactory();
		Session session = factory.openSession();
		Transaction t = session.beginTransaction();

		String hql = "SELECT s FROM Student s WHERE s.sEmail=:email AND s.sPass=:password";
		TypedQuery<Student> query = session.createQuery(hql, Student.class);
		query.setParameter("email",inputEmail);
		query.setParameter("password",inputPass);
		
		try {
			Student result = query.getSingleResult();
			validated = true;
			System.out.println("User account is valid");
		}catch(Exception e) {
			validated = false;
			System.out.println("User account is invalid");
		}
				
		t.commit();
		factory.close();
		session.close();
		
		return validated;
	}

	// After a successful student validation, this method takes a Student’s email and a Course ID.
	//It checks in the join table (i.e. Student_Course) generated by JPA to find if a Student with that Email is currently attending a Course with that ID
	public void registerStudentToCourse(String inputEmail, int inputId) {
		// TODO Auto-generated method stub
		
	}

	// This method takes a Student’s Email as a parameter and would find all the courses a student is registered for.
	public List<Course> getStudentCourses(String inputEmail) {
		// TODO Auto-generated method stub
		return null;
	}

}
